### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by freekmurze** [shift31/laravel-elasticsearch#11]
Hi,

could you modify the composer.json file so this package can be used in Laravel 5?

**Comment by bgetsug** [comment]
Yep, I should be able to get to it this weekend.

**Comment by bgetsug** [comment]
Actually, it looks like there are issues with the ServiceProvider that will prevent this package from working with Laravel 5...at least in its current development state.  I'll see what I can do, but I don't feel comfortable committing to anything until an L5 beta is released.

**Comment by bgetsug** [comment]
Initial support for Laravel 5 has been added in version 1.3.2 (also available in the develop and master branches).  Please use 'Shift31\LaravelElasticsearch\ElasticsearchServiceProvider' with Laravel 5.
