### ISSUE TITLE
About CRUD operations

### ISSUE THREAD

**Issue by MarcioMansurR** [shift31/laravel-elasticsearch#12]
Hello.

Do you have a simple example of how to update a document data using the function update, ate the "Client.php" file? I need to set a new field on my document e update others. Thank you.

**Comment by bgetsug** [comment]
This library is simply a wrapper for the official elasticsearch client for PHP.  Given the nature of your question, please raise an issue on their GitHub page:  https://github.com/elasticsearch/elasticsearch-php/issues.
