### ISSUE TITLE
Scroll / Scan results in a 404 error

### ISSUE THREAD

**Issue by csabo** [shift31/laravel-elasticsearch#13]
Hello again! we are having issues with Scroll. I've pasted the output below.  If we manually take that generated URL and use curl on it, we see the data results. ANY help would be amazing!

[Elasticsearch\Common\Exceptions\Missing404Exception]
  {"_scroll_id":"c2NhbjswOzE7dG90YWxfaGl0czo2MjIxOw==","took":11,"timed_out":false,"_shards":{"total":5,"successful":0,"failed":5,"failures":
  [{"status":404,"reason":"SearchContextMissingException[No search context found for id [216741]]"},{"status":404,"reason":"SearchContextMiss
  ingException[No search context found for id [216743]]"},{"status":404,"reason":"SearchContextMissingException[No search context found for i
  d [216745]]"},{"status":404,"reason":"SearchContextMissingException[No search context found for id [216742]]"},{"status":404,"reason":"Sear
  chContextMissingException[No search context found for id [216744]]"}]},"hits":{"total":6221,"max_score":0.0,"hits":[]}}

  [Guzzle\Http\Exception\ClientErrorResponseException]
  Client error response
  [status code] 404
  [reason phrase] Not Found
  [url] http://10.0.1.223:9200/_search/scroll/c2Nhbjs1OzIxNjc0MTpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzIxNjc0MzpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzIxNjc
  0NTpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzIxNjc0MjpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzIxNjc0NDpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzE7dG90YWxfaGl0czo2MjIxOw
  ==?scroll=1m

**Comment by bgetsug** [comment]
This library is simply a wrapper for the official elasticsearch client for PHP.  Given the nature of your error, please open a ticket on their GitHub page:  https://github.com/elasticsearch/elasticsearch-php/issues.
