### ISSUE TITLE
Guzzle update

### ISSUE THREAD

**Issue by sschimmel** [shift31/laravel-elasticsearch#14]
Hi,

Just installed via composer which gave me the following warnings/errors:

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

Is it possible to switch to guzzle/guzzle?

**Comment by bgetsug** [comment]
As this library is simply a wrapper for the official Elasticsearch PHP client, you'll likely need to file an issue in that repository:  https://github.com/elasticsearch/elasticsearch-php.  For the record, I believe you can safely ignore those warnings, as while earlier versions of Guzzle have been deprecated, the source is still available and functional.
