### ISSUE TITLE
Change Readme for Laravel 5 users

### ISSUE THREAD

**Issue by Tobiasartz** [shift31/laravel-elasticsearch#15]
In your readme you give the following example for using the Es client through a facade:
```
$result = Es::search($searchParams);
```

In Laravel 5 this only works when you add a use declaration at the top:
```
use Shift31\LaravelElasticsearch\Facades\Es
```

Or by adding a backslash to the facade:
```
$result = \Es::search($searchParams);
```

**Comment by bgetsug** [comment]
This doesn't just apply to Laravel 5.  Facades have always existed in the global namespace, so if you happen to be using one in a custom class (in its own namespace), importing the Facade with a 'use' statement is required. I think the confusion comes from the fact that typical Laravel 4 Controllers *also* exist in the global namespace, so importing is not necessary, but this was changed in Laravel 5.

I'm happy to update the README to remind developers to import the Facade as needed, but this should be version agnostic.

**Comment by paulocoghi** [comment]
Also, this is more an issue about changing from L4 to L5 and the use of namespaces by default.

**Comment by bgetsug** [comment]
Finally got around to updating the README in 5341998fc1d87a21ee44e44482d07de297b1b515
