### ISSUE TITLE
compatibility with Laravel 5.1 ?

### ISSUE THREAD

**Issue by frednotet** [shift31/laravel-elasticsearch#17]
Hi,

I try to use your Service Provider with my fresh install of Laravel 5.1 but i have some problems with composer : 

1° "guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)"

2° "Your requirements could not be resolved to an installable set of packages."

Problem 1
    - Conclusion: remove laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.2
    - Installation request for shift31/laravel-elasticsearch 1.0.*@dev -> satisfiable by shift31/laravel-elasticsearch[1.0.x-dev].
    - Conclusion: don't install laravel/framework v5.1.1
    - Conclusion: don't install laravel/framework v5.1.0
    - shift31/laravel-elasticsearch 1.0.x-dev requires illuminate/support ~4 -> satisfiable by illuminate/support[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, v4.0.0, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0-BETA1, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support 4.0.x-dev|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support 4.1.x-dev|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support 4.2.x-dev|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.0|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.0-BETA2|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.0-BETA3|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.0-BETA4|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.1|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.10|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.2|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.3|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.4|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.5|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.6|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.7|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.8|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.0.9|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.0|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.1|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.10|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.11|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.12|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.13|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.14|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.15|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.16|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.17|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.18|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.19|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.2|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.20|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.21|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.22|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.23|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.24|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.25|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.26|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.27|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.28|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.29|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.3|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.30|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.4|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.5|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.6|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.7|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.8|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.1.9|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.0-BETA1|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.1|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.12|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.16|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.17|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.2|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.3|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.4|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.5|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.6|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.7|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.8|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v4.2.9|don't install laravel/framework 5.1.x-dev
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.2].

Is that just me or... ? 

Thanks for your help,

**Comment by danmichaelo** [comment]
Did you use a version constraint when trying to install `shift31/laravel-elasticsearch`? I just installed the package successfully with Laravel 5.1 using `composer require shift31/laravel-elasticsearch ~1.0`

Here's my require-block in composer.json:

```json
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "danmichaelo/quitesimplexmlelement": "~0.2",
        "elasticsearch/elasticsearch": "~1.0",
        "shift31/laravel-elasticsearch": "~1.0"
    },
```

Excerpt from `composer show -i` :
```
elasticsearch/elasticsearch           v1.3.4             PHP Client for Elasticsearch
laravel/framework                     v5.1.3             The Laravel Framework.
shift31/laravel-elasticsearch         1.3.2              A Laravel Service Provider for the Elasticsearch API client
```

**Comment by bgetsug** [comment]
I've been unable to replicate this, and I've updated the README to demonstrate use of a version constraint with `composer require`.
