### ISSUE TITLE
increment counter in ES

### ISSUE THREAD

**Issue by Namiastek** [shift31/laravel-elasticsearch#20]
Is there any support for ES update, or maybe i'm not using it's the right way,
right here https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html
i found a script way to increment value without making any select to get actual value, yet when i tried use it as params i get error like this
{"error":"MapperParsingException[object mapping for [event] tried to parse field [script] as object, but got EOF, has a concrete value been provided to it?]","status":400}
is there any way to use Es::update($params); to increment some value ?

**Comment by bgetsug** [comment]
If you're using the latest version of this package (released today), partial updates should work as documented here: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_updating_documents.html.
