### ISSUE TITLE
Where I can see the more complex documentatin?

### ISSUE THREAD

**Issue by protectedfor** [shift31/laravel-elasticsearch#21]
Where I can see how to add to index using Laravel 5, for example?

**Comment by hamstu** [comment]
@protectedfor As the documentation states, this is nothing more than a simple Facade for accessing the underlying `Elasticsearch\Client` from the [official elasticsearch-php library](https://github.com/elastic/elasticsearch-php).

> Use the Es facade to access any method from the Elasticsearch\Client class, for example:
> `$searchParams['index'] = 'your_index';`
> `...`
> `$result = Es::search($searchParams);`

So for indexing, look in the documentation here: https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_indexing_documents.html

The only thing you change is when you see:

    $client->index($params);

You would instead write:

    Es::index($params);
