### ISSUE TITLE
Pagination Example

### ISSUE THREAD

**Issue by D-David11** [shift31/laravel-elasticsearch#22]
Hello, Can you please provide pagination example ? The doc you have provided is very short. Many things you should provide in that.

**Comment by bgetsug** [comment]
As this package is simply providing the Laravel "wiring" for the elasticsearch PHP client, I believe you'll need to consult their documentation. Maybe consider the scan/scroll functionality mentioned here: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_search_operations.html
