### ISSUE TITLE
Mapping support

### ISSUE THREAD

**Issue by nexana** [shift31/laravel-elasticsearch#23]
Does the package support mapping as explained in https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#_example_mapping ?

**Comment by bgetsug** [comment]
This package should support everything that the current elasticsearch PHP client does: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/index.html

https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_index_management_operations.html
