### ISSUE TITLE
Issues about 2.0 release

### ISSUE THREAD

**Issue by yuripave** [shift31/laravel-elasticsearch#26]
The ~2.0 release is completely broken at this moment. Since this package has some [popularity](https://packagist.org/packages/shift31/laravel-elasticsearch) and [featured](https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_community_integrations.html) by official, you should not merge #19, #24 and #25 and tag new release without testing.

1. In #24 and #25 logPath and logLevel config has been removed, v2 equivalent is [Elasticsearch/ClientBuilder::defaultLogger](https://github.com/elastic/elasticsearch-php/blob/v2.2.1/src/Elasticsearch/ClientBuilder.php#L181) then [Elasticsearch/ClientBuilder::setLogger](https://github.com/elastic/elasticsearch-php/blob/v2.2.1/src/Elasticsearch/ClientBuilder.php#L181).
2. In #24 and #25 actually the hosts config is not used at all because the [return statement](https://github.com/shift31/laravel-elasticsearch/pull/24/files#diff-5122ba3d89ee2a7d713f9bbf5edb55d8R38) just create a new builder instance and build the client. See [Elasticsearch/ClientBuilder::create](https://github.com/elastic/elasticsearch-php/blob/v2.2.1/src/Elasticsearch/ClientBuilder.php#L88).

More info on official doc:
https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_breaking_changes_from_1_x.html
https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_configuration.html

**Comment by bgetsug** [comment]
Sorry for the inconvenience. Version 2.0.3 is working for me with a local elasticsearch (2.3.5) server.

**Comment by yuripave** [comment]
Yes only localhost work because of below:
https://github.com/elastic/elasticsearch-php/blob/v2.2.1/src/Elasticsearch/ClientBuilder.php#L417
