### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by BlakeGardner** [shift31/laravel-elasticsearch#29]
I noticed that there is no license attached to this library. May i suggest licensing it under the MIT license and dropping a `LICENSE.md` file in the repo with a copy?

https://opensource.org/licenses/MIT has a good copy.

This could have been a pull request but it is more appropriate for the original author to explicitly state the license under which the code is released.

**Comment by candasm** [comment]
@BlakeGardner I have added LICENCE file in master repository today with latest version. 
Thank you for your help.
