### ISSUE TITLE
Support for 5.x?

### ISSUE THREAD

**Issue by j3j5** [shift31/laravel-elasticsearch#30]
Hi, are you planning to add support for 5.x version of ES?

I think adding the support on the composer file would do. I've been testing with the 5.0 version of `elasticsearch/elasticsearch` and everything seems to work. Shall I make a PR?

**Comment by pabloroman** [comment]
I second this

**Comment by candasm** [comment]
Hello,

We are planning to adding support for elastic search 5.x support. We added it in milestone. I will be happy to see your pr. But before please check our project tasks and milestones.

**Comment by candasm** [comment]
Elasticsearch 5.x support added for laravel 4.2 service provider. Pull request #39
