### ISSUE TITLE
Laravel 4.2 + PHP7 support isn't installable.

### ISSUE THREAD

**Issue by Ardakilic** [shift31/laravel-elasticsearch#44]
Hello,

I'm trying to use Laravel-elasticsearch for ES1.x with PHP7 support. So I've added 4.1.* as version.

```
composer require shift31/laravel-elasticsearch:4.1.*
```

However, when it starts to install, I get an error like this:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - shift31/laravel-elasticsearch v4.1.1 requires php >=5.4.0 <=7.0 -> your PHP version (7.0.15) does not satisfy that requirement.
    - shift31/laravel-elasticsearch v4.1.0 requires php >=5.4.0 <=7.0.0 -> your PHP version (7.0.15) does not satisfy that requirement.
    - Installation request for shift31/laravel-elasticsearch 4.1.* -> satisfiable by shift31/laravel-elasticsearch[v4.1.0, v4.1.1].
```

So, I'm stuck here. Since Laravel 4.2.20, [Laravel 4 can run on PHP7](https://twitter.com/laravelphp/status/791302938027184128).

I'd appreciate if this could be resolved.

Thanks in advance!

**Comment by candasm** [comment]
Hello @Ardakilic,

Can you please send a pull request for 4.1 branch?
