### ISSUE TITLE
Plans for PHP 7.1+ support?

### ISSUE THREAD

**Issue by latelatelate** [shift31/laravel-elasticsearch#50]
Hey,

Thanks for your hard work! Do you have plans on supporting php 7.1+ at some point? Would love to continue using this package, but 4.5 is broken now w/ 7.1.3 ;[

`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for shift31/laravel-elasticsearch 4.5.0 -> satisfiable by shift31/laravel-elasticsearch[v4.5.0].
    - shift31/laravel-elasticsearch v4.5.0 requires php >=5.6 <=7.1 -> your PHP version (7.1.3) does not satisfy that requirement.

Installation failed, reverting ./composer.json to its original content.
`

**Comment by candasm** [comment]
Hello @latelatelate ,

  Actually I didn't have time to test with PHP 7.1+ thats why I lock it. If you test it and works without limitation, you can make a pull request for changes.

**Comment by candasm** [comment]
Its already fixed on [4.5 branch](https://github.com/shift31/laravel-elasticsearch/blob/4.5/composer.json#L11).
