### ISSUE TITLE
Request for uses Documentation

### ISSUE THREAD

**Issue by kushal555** [shift31/laravel-elasticsearch#51]
Hello @bgetsug ,
Really thank you very much. I really much existed when I see this package. Actually, before Laravel I am working with symfony2. It also have a good Package for [Elastica Search](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/index.md)
Which is well documented. So I just request you to please describe a little bit more, like where we need to put the configuration related to the index. where we need to declare indexes how to attach with model and all.
As I attached the link of Symfony bundle So that we can have the idea exactly how can we also integrate this Good Package in Laravel.

Thank you.

**Comment by candasm** [comment]
Hello @kushal555,

[laravel-elasticsearch](https://github.com/shift31/laravel-elasticsearch) package is an service provider for official [elasticsearch-php](https://github.com/elastic/elasticsearch) package.

So basically you just use ES Facade or inject es client to your controllers or models wherever you wanna use. Also this documented in readme file.
